### PR TITLE
Corrected import name + Docs typos

### PR DESCRIPTION
**Pull request by cohawk**

### CODE REVIEW

**Comment by cohawk** [comment]
another slight annoyance I came across (that I do not have a good solution for) when pulling these libs from GitHub was the usage of **underscores** in [live_view_native](https://github.com/liveview-native/live_view_native) and **dashes** in [liveview-client-swiftui](https://github.com/liveview-native/liveview-client-swiftui)

I know Elixir/Phoenix primarily use underscores, while Apple/SwiftUI use dashes - but that did not stop me from staring at this for 10mins of `mix deps.get` output before realizing, so others might have similar issue.

```
{:live_view_native, git: "https://github.com/liveview-native/live-view-native.git", override: true},
{:live_view_native_swiftui, git: "https://github.com/liveview-native/liveview-client-swiftui.git"}
```

**Comment by bcardarella** [comment]
@cohawk could you please rebase this against `main`?

**Comment by cohawk** [comment]
I’m away from terminal for a bit

with the minimal amount of typos probably easier for @BrooklinJazz to just copy them into a new PR

**Comment by BrooklinJazz** [comment]
closing in favor of: https://github.com/liveview-native/live_view_native/pull/174

**Pull request closed without merging**
