### PR TITLE
LVN template parser

### PR DESCRIPTION
**Pull request by bcardarella**

### CODE REVIEW

**Comment by bcardarella** [comment]
This PR will provide a Floko-compatible template parser

This enables completing `inputs_for/1` and getting the test suite ready for integration testing LVN

**Comment by leandrocp** [comment]
Hey @bcardarella that's interesting. You might want to take a look at https://github.com/philss/floki/issues/463
Floki has introduced attrs as maps to facilitate testing so it might be useful for LVN as well.

**Comment by bcardarella** [comment]
Good catch! That should be fairly easy to implement once I cover some more of the edge cases in the parser

**Comment by bcardarella** [comment]
@leandrocp done: https://github.com/liveview-native/live_view_native/pull/208/commits/828708dfef7a8e5f1a95f8d5972c91d80dfaf10a

**Pull request merged**
