### PR TITLE
Change `~Z` sigil to `~LVN`, allow custom render macros

### PR DESCRIPTION
**Pull request by supernintendo**
[Elixir 1.15](https://hexdocs.pm/elixir/main/changelog.html) adds support for multi-letter sigils; this PR replaces the placeholder sigil `~Z` with `~LVN` for rendering inline HEEx templates for LiveView Native platforms:

```elixir
defmodule ScratchboardWeb.HelloLive do
  use Phoenix.LiveView
  use LiveViewNative.LiveView

  @impl true
  def render(%{platform_id: :swiftui} = assigns) do
    ~LVN"""
    <VStack id="hello-ios">
      <HStack modifiers={@native |> padding(all: 5)}>
        <Text>Hello iOS!</Text>
      </HStack>
    </VStack>
    """swiftui
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div id="hello-web">
      <div class="text-slate-800 bg-slate-50 h-screen w-screen grid grid-cols-1 gap-1 content-center items-center text-center">
        <div class="font-semibold mb-1">Hello web!</div>
      </div>
    </div>
    """
  end
end
```

The `~Z` sigil is left intact as an alias of `~LVN`. It will be removed in a future version of `live_view_native` and causes a compiler warning when used:

```
warning: sigil_Z/2 is deprecated. Please use sigil_LVN/2 instead.
```

Related PR: https://github.com/liveview-native/live_view_native_platform/pull/5

### CODE REVIEW

**Comment by josevalim** [comment]
What do you think about using one per platform? Such as `~SWI` and `~JET`? I think it will read better and more concise than `~LVN"..."jetpack`?

**Comment by bcardarella** [comment]
@josevalim The reason we went with the modifiers was so we don't spam the sigil with many client names. We will be adding a winui3 client at some point and potentially other clients as we see fit. And with all of the LV document merging and network code extracted into Core others can create clients

We felt it was best to have the single `LVN` sigil with an api to register new modifiers

**Comment by josevalim** [comment]
I think that made sense pre-Elixir v1.15 but with the new version you can create as many sigils as you want. You can even have a macro for defining the sigils for new platforms. So without the technical restriction, I would focus on what provides better user experience (which may be ~LVN, your call ofc). :)

**Comment by bcardarella** [comment]
I was actually thinking that we could make the modifier optionally implicit. I believe that we can extract the platform id from the `assigns` within the sigil macro and set this as the modifier. This way only:

```
~LVN"""
<template here/>
"""
```

is necessary. One concept I have in mind for the future is a single template system that can compile to the platform specific templates. This gives LVN a unified UI that can be used for rapid prototyping and application building:

```
~LVNUI"""
<Text>Foobar</Text>
"""
```

This would then detect the platform id and render the platform equivalent of the unified UI markup.

**Review by carson-katri — APPROVED** [review]

**Comment by supernintendo** [comment]
@bcardarella I don't think that will work unfortunately, since sigils are macros and template compilation is done at compile-time so there would be no assigns to reference in that context. LiveView Native HEEx templates can't really be shared across platforms either since each platform has its own configuration that could influence which tag handler should be used, imported modifier functions, etc.

I like @josevalim's idea of supporting different sigils per platform though. This will require changes to a few other repos:

- [live_view_native_platform](https://github.com/liveview-native/live_view_native_platform) which provides the protocols that LVN platform libraries implement
- [liveview-client-swiftui](https://github.com/liveview-native/)
- [liveview-client-jetpack](https://github.com/liveview-native/liveview-client-jetpack) (in [this PR](https://github.com/liveview-native/liveview-client-jetpack/pull/61))

It's not a huge lift though. I can create PRs for all of that today if this is the path we want to take 🙂

**Comment by bcardarella** [comment]
@supernintendo I thought you could access it similar to how `sigil_H` is doing here: https://github.com/phoenixframework/phoenix_live_view/blob/3d7a3bace5ba5ff54359e7d2e21f96b5236579c0/lib/phoenix_component.ex#L749-L751

**Comment by supernintendo** [comment]
@bcardarella That only checks that the `assigns` variable is defined at compile time though, not the actual value of it. I don't think its possible to match on the actual contents of the assigns map which is needed to determine the `platform_id` of the client (`:swiftui`, `:jetpack` etc.). This can only be known at runtime, when a client connects to the Phoenix backend.

**Pull request merged**
